'use client';
import { useState, type FormEvent } from 'react';
import { ArrowUpRight, ArrowRight, Download, MapPin, Mail, Phone, Linkedin, Menu, X, Activity, Monitor, Wrench, Search, Settings, ClipboardCheck, GraduationCap, Code2, CalendarDays, Stethoscope, Check } from 'lucide-react';
const linkedin = 'https://www.linkedin.com/in/kareem-qashqoush/';
const email = 'kareemqashqoush@gmail.com';
import { useLocale } from './locale';
import { Experience, Identity } from './experience';
import { TrainingGallery } from './training-gallery';
import trainingMedia from './training-media.json';
const skills = ['Next.js', 'React', 'JavaScript', 'Node.js', 'SQL', 'HTML', 'Power BI'];
const training = [
    { id: 'siemens', name: 'Siemens', date: 'September 2024', type: 'Medical imaging', text: 'Training on MRI, CT, and Cath Lab systems, with a focus on troubleshooting and diagnostics.', icon: Activity },
    { id: 'true-medical', name: 'True Medical · Mindray', date: 'July – August 2024', type: 'Sales & applications', text: 'Customer communication, requirement analysis, negotiation, and medical product understanding.', icon: Monitor },
    { id: 'dar-al-fouad', name: 'Dar Al Fouad Hospital', date: 'January – February 2024', type: 'Clinical engineering', text: 'Maintenance exposure across CT systems, infusion pumps, and dialysis machines.', icon: Wrench },
    { id: 'childrens-hospital', name: "Children’s Hospital", date: 'August 2023 · 60 hours', type: 'Hospital training', text: 'Clinical engineering exposure and an understanding of hospital medical equipment operations.', icon: Stethoscope },
    { id: 'bahya-july', name: 'BAHYA Foundation', date: 'July 2023 · 60 hours', type: 'Oncology & radiotherapy', text: 'Exposure to oncology and radiotherapy systems and medical equipment workflows.', icon: Activity },
    { id: 'bahya-january', name: 'BAHYA Foundation', date: 'January 2023 · 6 hours', type: 'Biomedical foundations', text: 'An introduction to biomedical engineering applications in a clinical environment.', icon: GraduationCap },
];
function Brand() { const { t } = useLocale(); return <a className="brand" href="#home" aria-label={t("Kareem home")}><span>K</span>{t("Kareem")}<span className="brand-dot">.</span></a>; }
export default function Home() {
    const { t, locale, toggle } = useLocale();
    const [menu, setMenu] = useState(false);
    const [contactReady, setContactReady] = useState(false);
    function contact(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const d = new FormData(e.currentTarget); const body = `${locale === 'ar' ? 'مرحبًا كريم،' : 'Hi Kareem,'}\n\n${d.get('message')}\n\n${d.get('name')}\n${d.get('email')}\n${d.get('location') || ''}`; window.location.href = `mailto:${email}?subject=${encodeURIComponent(String(d.get('subject')))}&body=${encodeURIComponent(body)}`; setContactReady(true); }
    return <Experience><a className="skip-link" href="#main">{t("Skip to content")}</a><header><div className="container nav"><Brand /><div className="nav-actions"><button className="language-switch" type="button" onClick={() => { toggle(); setMenu(false); }} aria-label={locale === 'ar' ? 'Switch to English' : 'التبديل إلى العربية'} lang={locale === 'ar' ? 'en' : 'ar'}><span aria-hidden="true">◎</span>{locale === 'ar' ? 'English' : 'العربية'}</button><button className="menu-toggle" aria-label={menu ? t("Close navigation") : t("Open navigation")} aria-expanded={menu} aria-controls="navigation" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div><nav id="navigation" className={menu ? 'open' : ''}>{[[t("Home"), 'home'], [t("About"), 'about'], [t("Experience"), 'experience'], [t("Training"), 'training'], [t("Skills"), 'skills']].map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<a className="button" href="#contact" onClick={() => setMenu(false)}>{t("Contact")}</a></nav></div></header>
 <main id="main"><div className="intro-bg"><section id="home" className="container hero"><div className="hero-copy"><div className="eyebrow"><span />{" " + t("BIOMEDICAL ENGINEER & DEVELOPER") + ""}</div><h1>{t("Hello, I\u2019m")}<br />{t("Kareem")}<br /><span>{t("Qashqoush.")}</span></h1><p>{"" + t("I connect") + " "}<strong>{t("medical technology")}</strong>{" " + t("with") + " "}<strong>{t("healthcare software")}</strong>{" " + t("\u2014 helping clinical teams work better through reliable equipment and thoughtful digital solutions.") + ""}</p><div className="actions hero-actions"><a className="button" href="/Kareem-Qashqoush-CV.pdf" download><Download size={18}/>{t("Download CV")}</a><a className="button secondary" href={linkedin} target="_blank" rel="noreferrer"><Linkedin size={18}/>{t("LinkedIn")}<ArrowUpRight size={17}/></a></div><div className="stats"><div><strong>3.2<span>/4</span></strong><small>{t("University GPA")}</small></div><div><strong>6</strong><small>{t("Training experiences")}</small></div><div><strong>2</strong><small>{t("Connected disciplines")}</small></div></div></div><Identity /></section>
 <section id="about" className="container about"><div className="about-visual"><Identity small/><a className="social-pill" href={linkedin} target="_blank" rel="noreferrer" aria-label={t("Kareem on LinkedIn")}><Linkedin size={20}/> <span>{t("Let\u2019s connect on LinkedIn")}</span><ArrowUpRight size={18}/></a></div><div><span className="eyebrow">{t("A LITTLE ABOUT ME")}</span><h2>{t("Engineering better")}<br />{t("healthcare experiences.")}</h2><p>{t("I\u2019m Kareem Mohamed Qashqoush, a Biomedical Engineering graduate from Mansoura University. My experience spans clinical engineering, medical device support, and healthcare software development.")}</p><p>{t("From supporting imaging systems to building clinic management platforms, I translate technical and clinical requirements into practical solutions.")}</p><div className="actions"><a href="#experience" className="button">{"" + t("My experience") + " "}<ArrowRight size={17}/></a><a href="/Kareem-Qashqoush-CV.pdf" className="button secondary" download><Download size={18}/>{t("Download CV")}</a></div></div></section></div>
 <section className="process-section"><div className="container process"><div><span className="eyebrow">{t("HOW I APPROACH THE WORK")}</span><h2>{t("From clinical needs")}<br />{t("to practical solutions.")}</h2><p>{t("Healthcare works best when people and technology work together. My approach combines clear communication, technical problem solving, and attention to real clinical workflows.")}</p></div><div className="process-grid">{[{ i: Search, t: t("Understand"), d: t("Listen to clinical teams and identify the requirements behind the problem.") }, { i: Settings, t: t("Analyze"), d: t("Assess technical needs, equipment performance, and existing workflows.") }, { i: Code2, t: t("Implement"), d: t("Configure medical technology or develop usable healthcare software.") }, { i: ClipboardCheck, t: t("Support"), d: t("Troubleshoot issues and help staff use systems with confidence.") }].map((p, i) => <article className="process-card" key={i}><div className="icon-box"><p.i size={25}/></div><h3>{i + 1}. {p.t}</h3><p>{p.d}</p></article>)}</div></div></section>
 <section id="experience" className="container section"><div className="section-heading"><span className="eyebrow">{t("WHERE I\u2019VE CONTRIBUTED")}</span><h2>{t("Professional experience")}</h2><p>{t("Hands-on work at the intersection of medical devices and digital healthcare.")}</p></div><div className="experience-list"><article className="experience-card"><div className="job-icon"><Activity size={30}/></div><div className="job-main"><div className="job-top"><span className="label">{t("MEDICAL TECHNOLOGY")}</span><span className="date">{t("Sep 2025 \u2014 Present")}</span></div><h3>{t("Application and Product Specialist")}</h3><h4>{"" + t("BM-Egypt (Mindray)") + " "}<span>{t("\u00B7 Mansoura, Egypt")}</span></h4><ul><li>{t("On-site technical support and troubleshooting for imaging devices.")}</li><li>{t("Assisted medical staff with proper device operation.")}</li><li>{t("Installed and configured flat panel detector systems.")}</li><li>{t("Supported system performance and minimized downtime.")}</li></ul></div></article><article className="experience-card"><div className="job-icon"><Code2 size={30}/></div><div className="job-main"><div className="job-top"><span className="label">{t("HEALTHCARE SOFTWARE")}</span><span className="date">{t("Oct 2024 \u2014 Jan 2026")}</span></div><h3>{t("Healthcare Software Developer")}</h3><h4>{"" + t("Freelance") + " "}<span>{t("\u00B7 Remote")}</span></h4><ul><li>{t("Developed web-based systems for clinic and hospital management.")}</li><li>{t("Built appointment scheduling, patient records, and administrative workflows.")}</li><li>{t("Contributed to system design and UI/UX for medical platforms.")}</li><li>{t("Translated healthcare requirements into usable software for doctors, receptionists, and administrators.")}</li></ul></div></article></div></section>
 <section className="cta"><div className="container"><span className="eyebrow">{t("LET\u2019S BUILD SOMETHING USEFUL")}</span><h2>{t("Better technology.")}<br />{t("Better healthcare workflows.")}</h2><p>{t("Have an opportunity in Health IT or Clinical Engineering?")}<br />{t("I\u2019d love to hear about it.")}</p><a href="#contact" className="button">{"" + t("Let\u2019s work together") + " "}<ArrowRight size={19}/></a></div></section>
 <section id="training" className="container section"><div className="section-heading"><span className="eyebrow">{t("LEARNING IN THE FIELD")}</span><h2>{t("Clinical & technical training")}</h2><p>{t("Experience across imaging, hospital equipment, and medical applications.")}</p></div><div className="training-grid">{training.map((item, i) => <article className="training-card" key={item.name + item.date}><TrainingGallery images={trainingMedia[item.id as keyof typeof trainingMedia]} title={t(item.name)} icon={item.icon} number={i}/><div className="training-content"><span className="label">{t(item.type)}</span><h3>{t(item.name)}</h3><p>{t(item.text)}</p><div className="training-date"><CalendarDays size={15}/>{t(item.date)}</div></div></article>)}</div></section>
 <section id="skills" className="skills-section"><div className="container skills-layout"><div><span className="eyebrow">{t("MY TOOLKIT")}</span><h2>{t("What I bring")}<br />{t("to the team.")}</h2><p>{t("A biomedical foundation, a developer\u2019s mindset, and the ability to communicate across technical and clinical teams.")}</p><a className="button" href="#contact">{"" + t("Get in touch") + " "}<ArrowUpRight size={18}/></a></div><div className="service-list"><article><Activity /><div><h3>{t("Medical imaging & equipment")}</h3><p>{t("X-ray, CT, and MRI systems. Equipment installation, troubleshooting, preventive maintenance, and electronics fundamentals.")}</p></div></article><article><Monitor /><div><h3>{t("Healthcare software development")}</h3><p>{t("Web applications that support patient records, appointments, and day-to-day clinical administration.")}</p><div className="skill-tags">{skills.map(s => <span key={s}>{s}</span>)}</div></div></article><article><Stethoscope /><div><h3>{t("Clinical & technical collaboration")}</h3><p>{t("Communication, teamwork, problem solving, time management, presentation, negotiation, and customer service.")}</p></div></article></div></div></section>
 <section className="container section education-section"><div className="section-heading"><span className="eyebrow">{t("BUILT ON A STRONG FOUNDATION")}</span><h2>{t("Education & continued learning")}</h2></div><div className="education-card"><div className="icon-box"><GraduationCap size={30}/></div><div><h3>{t("Bachelor of Biomedical Engineering")}</h3><p>{t("Mansoura University \u00B7 2020 \u2013 January 2025")}</p></div><span className="grade">{"" + t("Very Good") + " "}<strong>{t("3.2 / 4 GPA")}</strong></span></div><div className="course-list">{[[t("Medical Planning"), t("Dec 2024")], [t("Clinical Course"), t("Jul 2024")], [t("FrontEnd \u00B7 React.js"), t("Jan \u2013 Jun 2024")], [t("MRI & CT"), t("Sep 2023")], [t("Sales"), t("May 2023")], [t("Project Management (PMT)"), t("Sep 2022")], [t("Marketing"), t("Aug 2022")], [t("Employment Skills"), t("Jul 2022")]].map(([c, d], i) => <div key={i}><Check size={16}/><span>{c}</span><small>{d}</small></div>)}</div><div className="language-row"><span>{t("LET\u2019S TALK")}</span><strong>{t("Arabic")}</strong><span className="divider"/><strong>{t("English")}</strong></div></section>
 <div className="contact-wrap"><section id="contact" className="container contact-card"><div><span className="eyebrow">{t("SAY HELLO")}</span><h2>{t("Let\u2019s discuss")}<br />{t("your next opportunity.")}</h2><p>{t("For roles, collaborations, or a conversation about healthcare technology \u2014 reach out.")}</p><div className="contact-details"><div><span className="icon-box"><MapPin size={22}/></span><span><small>{t("Based in")}</small><strong>{t("Taif, Saudi Arabia")}</strong></span></div><a href={`mailto:${email}`}><span className="icon-box"><Mail size={22}/></span><span><small>{t("Email me")}</small><strong dir="ltr">{email}</strong></span></a><a href="tel:+966531469302"><span className="icon-box"><Phone size={22}/></span><span><small>{t("Call me")}</small><strong dir="ltr">+966 53 146 9302</strong></span></a></div><a className="linkedin-button" href={linkedin} target="_blank" rel="noreferrer"><Linkedin size={20}/>{"" + t("LinkedIn") + " "}<ArrowUpRight size={16}/></a></div><form onSubmit={contact}><p>{t("Tell me a little about what you have in mind.")}</p><label>{t("Your name")}<input required name="name" autoComplete="name" placeholder={t("Name")} maxLength={100}/></label><label>{t("Email address")}<input required name="email" type="email" dir="ltr" autoComplete="email" placeholder="you@company.com" maxLength={200}/></label><div className="form-row"><label>{"" + t("Location") + " "}<span>{t("(optional)")}</span><input name="location" autoComplete="address-level2" placeholder={t("City, country")} maxLength={100}/></label><label>{t("Subject")}<input required name="subject" placeholder={t("Let\u2019s collaborate")} maxLength={200}/></label></div><label>{t("Message")}<textarea required name="message" placeholder={t("How can we work together?")} rows={3} maxLength={4000}/></label><button className="button" type="submit">{"" + t("Compose email") + " "}<ArrowUpRight size={18}/></button><small className="form-note" role="status">{contactReady ? t("Your email app should open with your draft. If it doesn\u2019t, use the email link alongside this form.") : t("Opens your email app with a ready-to-send draft.")}</small></form></section></div></main><footer><div className="container footer-inner"><Brand /><div><a href="#about">{t("About")}</a><a href="#experience">{t("Experience")}</a><a href="#contact">{t("Contact")}</a></div><small>© {new Date().getFullYear()}{" " + t("Kareem Qashqoush") + ""}</small></div></footer></Experience>;
}
